apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mail-instance
  namespace: test-stack
  labels:
    app: home-osb-broker
    namespace: osb-stack
spec:
  clusterServiceClassExternalName: mail-service
  clusterServicePlanExternalName: mail-free-plan
  parameters:
    max: 10