apiVersion: v1
kind: Service
metadata:
  name: home-osb-service
  namespace: osb-stack
spec:
  # Service will act as load balancer - selector is matching underling instance(s). There can be one or more Deployment(s) with the same selector label
  selector:
    # XX-YYY
    app: home-osb
  # Defining headless service
  #clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-osb-deployment
  labels:
    # This should be same as Service spec:selector
    # XX-YYY
    app: home-osb
  namespace: osb-stack
spec:
  # commenting the replicas as this will be controlled by HPA
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: home-osb
  template:
    metadata:
      labels:
        app: home-osb
        network/db-access: "false"
    spec:
      containers:
        - name: home-osb
          image: alokkusingh/home-osb:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 15
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Kolkata
            type: File